CREATE TABLE SIMS_CLASS(
    COLLEGE_ID VARCHAR2(32),
    MAJOR_ID VARCHAR2(32),
    CLASS_ID VARCHAR2(32) NOT NULL,
    CLASS_NAME VARCHAR2(90),
    STUDENT_NUMBER INT,
    ADVISER VARCHAR2(90),
    ESTAB_DATE DATE,
    YEAR_NUMBER INT,
    TENANT_ID VARCHAR2(32),
    REVISION INT,
    CREATED_BY VARCHAR2(32),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME DATE,
    PRIMARY KEY (CLASS_ID)
);

COMMENT ON TABLE SIMS_CLASS IS '班级';
COMMENT ON COLUMN SIMS_CLASS.COLLEGE_ID IS '所在学院';
COMMENT ON COLUMN SIMS_CLASS.MAJOR_ID IS '所属专业ID';
COMMENT ON COLUMN SIMS_CLASS.CLASS_ID IS '班级ID';
COMMENT ON COLUMN SIMS_CLASS.CLASS_NAME IS '班级名称';
COMMENT ON COLUMN SIMS_CLASS.STUDENT_NUMBER IS '班级人数';
COMMENT ON COLUMN SIMS_CLASS.ADVISER IS '辅导员';
COMMENT ON COLUMN SIMS_CLASS.ESTAB_DATE IS '成立时间';
COMMENT ON COLUMN SIMS_CLASS.YEAR_NUMBER IS '学习年数';
COMMENT ON COLUMN SIMS_CLASS.TENANT_ID IS '租户号';
COMMENT ON COLUMN SIMS_CLASS.REVISION IS '乐观锁';
COMMENT ON COLUMN SIMS_CLASS.CREATED_BY IS '创建人';
COMMENT ON COLUMN SIMS_CLASS.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN SIMS_CLASS.UPDATED_BY IS '更新人';
COMMENT ON COLUMN SIMS_CLASS.UPDATED_TIME IS '更新时间';

CREATE TABLE SIMS_STUDENT(
    COLLEGE_ID VARCHAR2(32) NOT NULL,
    CLASS_ID VARCHAR2(32) NOT NULL,
    STUDENT_ID VARCHAR2(32) NOT NULL,
    STUDENT_NAME VARCHAR2(90),
    ENG_NAME VARCHAR2(90),
    ID_CARD_NO VARCHAR2(255),
    MOBILE_PHONE VARCHAR2(255),
    GENDER VARCHAR2(32) DEFAULT  'M',
    MONTHLY_SALARY DECIMAL(24,6),
    BIRTH DATE,
    AVATAR INT,
    HEIGHT INT,
    WEIGHT INT,
    NATION VARCHAR2(32) DEFAULT  '01',
    POLITICAL VARCHAR2(32),
    MARITAL VARCHAR2(32) DEFAULT  'UNMARRIED',
    DOMICILE_PLACE_PROVINCE VARCHAR2(255),
    DOMICILE_PLACE_CITY VARCHAR2(255),
    DOMICILE_PLACE_ADDRESS VARCHAR2(255),
    HOBBY VARCHAR2(255),
    INTRO VARCHAR2(900),
    PRESENT_ADDRESS VARCHAR2(255),
    EMAIL VARCHAR2(255),
    ENTRY_DATE DATE,
    STATUS VARCHAR2(32) DEFAULT  'Normal',
    TENANT_ID VARCHAR2(32),
    REVISION INT,
    CREATED_BY VARCHAR2(32),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME DATE,
    PRIMARY KEY (STUDENT_ID)
);

COMMENT ON TABLE SIMS_STUDENT IS '学生';
COMMENT ON COLUMN SIMS_STUDENT.COLLEGE_ID IS '所在学院ID';
COMMENT ON COLUMN SIMS_STUDENT.CLASS_ID IS '所在班级ID';
COMMENT ON COLUMN SIMS_STUDENT.STUDENT_ID IS '学生ID';
COMMENT ON COLUMN SIMS_STUDENT.STUDENT_NAME IS '学生姓名';
COMMENT ON COLUMN SIMS_STUDENT.ENG_NAME IS '英文名';
COMMENT ON COLUMN SIMS_STUDENT.ID_CARD_NO IS '身份证号';
COMMENT ON COLUMN SIMS_STUDENT.MOBILE_PHONE IS '手机号';
COMMENT ON COLUMN SIMS_STUDENT.GENDER IS '性别';
COMMENT ON COLUMN SIMS_STUDENT.MONTHLY_SALARY IS '月薪';
COMMENT ON COLUMN SIMS_STUDENT.BIRTH IS '出生日期';
COMMENT ON COLUMN SIMS_STUDENT.AVATAR IS '头像';
COMMENT ON COLUMN SIMS_STUDENT.HEIGHT IS '身高';
COMMENT ON COLUMN SIMS_STUDENT.WEIGHT IS '体重';
COMMENT ON COLUMN SIMS_STUDENT.NATION IS '名族';
COMMENT ON COLUMN SIMS_STUDENT.POLITICAL IS '政治面貌';
COMMENT ON COLUMN SIMS_STUDENT.MARITAL IS '婚姻状况';
COMMENT ON COLUMN SIMS_STUDENT.DOMICILE_PLACE_PROVINCE IS '籍贯（省）';
COMMENT ON COLUMN SIMS_STUDENT.DOMICILE_PLACE_CITY IS '籍贯（市）';
COMMENT ON COLUMN SIMS_STUDENT.DOMICILE_PLACE_ADDRESS IS '户籍地址';
COMMENT ON COLUMN SIMS_STUDENT.HOBBY IS '爱好';
COMMENT ON COLUMN SIMS_STUDENT.INTRO IS '简要介绍';
COMMENT ON COLUMN SIMS_STUDENT.PRESENT_ADDRESS IS '居住地址';
COMMENT ON COLUMN SIMS_STUDENT.EMAIL IS '电子邮件';
COMMENT ON COLUMN SIMS_STUDENT.ENTRY_DATE IS '入学日期';
COMMENT ON COLUMN SIMS_STUDENT.STATUS IS '状态';
COMMENT ON COLUMN SIMS_STUDENT.TENANT_ID IS '租户号';
COMMENT ON COLUMN SIMS_STUDENT.REVISION IS '乐观锁';
COMMENT ON COLUMN SIMS_STUDENT.CREATED_BY IS '创建人';
COMMENT ON COLUMN SIMS_STUDENT.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN SIMS_STUDENT.UPDATED_BY IS '更新人';
COMMENT ON COLUMN SIMS_STUDENT.UPDATED_TIME IS '更新时间';


CREATE INDEX idx_smis_student_01 ON SIMS_STUDENT(STUDENT_NAME,ENG_NAME);
CREATE INDEX idx_smis_student_cert ON SIMS_STUDENT(ID_CARD_NO);

CREATE TABLE SIMS_TEACHER(
    COLLEGE_ID VARCHAR2(32) NOT NULL,
    TEACHER_ID VARCHAR2(32) NOT NULL,
    TEACHER_NAME VARCHAR2(90),
    GENDER VARCHAR2(32) DEFAULT  'M',
    BIRTH DATE,
    GRADUATE_INSTITUTION VARCHAR2(90),
    PRACTICE_YEARS INT,
    POLITICAL VARCHAR2(32),
    MARITAL VARCHAR2(32) DEFAULT  'UNMARRIED',
    AVATAR VARCHAR2(255),
    INTRO VARCHAR2(900),
    TENANT_ID VARCHAR2(32),
    REVISION INT,
    CREATED_BY VARCHAR2(32),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME DATE,
    PRIMARY KEY (TEACHER_ID)
);

COMMENT ON TABLE SIMS_TEACHER IS '教师';
COMMENT ON COLUMN SIMS_TEACHER.COLLEGE_ID IS '所在学院ID';
COMMENT ON COLUMN SIMS_TEACHER.TEACHER_ID IS '教师ID';
COMMENT ON COLUMN SIMS_TEACHER.TEACHER_NAME IS '姓名';
COMMENT ON COLUMN SIMS_TEACHER.GENDER IS '性别';
COMMENT ON COLUMN SIMS_TEACHER.BIRTH IS '出生日期';
COMMENT ON COLUMN SIMS_TEACHER.GRADUATE_INSTITUTION IS '毕业院校';
COMMENT ON COLUMN SIMS_TEACHER.PRACTICE_YEARS IS '从业年限';
COMMENT ON COLUMN SIMS_TEACHER.POLITICAL IS '政治面貌';
COMMENT ON COLUMN SIMS_TEACHER.MARITAL IS '婚姻状况';
COMMENT ON COLUMN SIMS_TEACHER.AVATAR IS '头像';
COMMENT ON COLUMN SIMS_TEACHER.INTRO IS '介绍';
COMMENT ON COLUMN SIMS_TEACHER.TENANT_ID IS '租户号';
COMMENT ON COLUMN SIMS_TEACHER.REVISION IS '乐观锁';
COMMENT ON COLUMN SIMS_TEACHER.CREATED_BY IS '创建人';
COMMENT ON COLUMN SIMS_TEACHER.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN SIMS_TEACHER.UPDATED_BY IS '更新人';
COMMENT ON COLUMN SIMS_TEACHER.UPDATED_TIME IS '更新时间';

